version: '3.7'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./master:/usr/local/etc/redis:rw
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    volumes:
      - ./slave01:/usr/local/etc/redis:rw
    command: 
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
      - "--slaveof"
      - "redis-master"
      - "6379"

  
  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    volumes:
      - ./slave02:/usr/local/etc/redis:rw
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
      - "--slaveof"
      - "redis-master"
      - "6379"

