version: '3.7'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
      - ./master/users.acl:/usr/local/etc/redis/users.acl
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    volumes:
      - ./slave01/redis.conf:/usr/local/etc/redis/redis.conf
      - ./slave01/users.acl:/usr/local/etc/redis/users.acl
    command: 
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
      - "--slaveof"
      - "redis-master"
      - "6379"

  
  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    volumes:
      - ./slave02/redis.conf:/usr/local/etc/redis/redis.conf
      - ./slave02/users.acl:/usr/local/etc/redis/users.acl
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
      - "--slaveof"
      - "redis-master"
      - "6379"

